config {
    type: "table",
    dependencies: ["questions_with_clusters"],
    tags: ["regenerate_question_themes"]
}

WITH
  summarization_prompt AS (
  SELECT
    centroid_id,
    CONCAT("Generate a concise theme that summarizes the general intent of the following questions. Do not include any markup in the response. \n\nQuestions: ", questions) AS prompt
  FROM (
    SELECT
      centroid_id,
      STRING_AGG(question, "\n\n") AS questions
    FROM (
      SELECT
        centroid_id,
        ROW_NUMBER() OVER (PARTITION BY centroid_id) AS question_count,
        question
      FROM
        ${ref("questions_with_clusters")} 
    WHERE
      question_count < 20
    GROUP BY
      centroid_id ) clustered_questions )
SELECT
  centroid_id AS cluster_id,
  ml_generate_text_llm_result AS theme
FROM
  ML.GENERATE_TEXT( 
    MODEL ${constants.PROJECT_ID}.${constants.SCHEMA_NAME}.bqml_text_llm,
    TABLE summarization_prompt,
    STRUCT( 1.0 AS temperature,
      64 AS max_output_tokens,
      0.2 AS top_p,
      5 AS top_k,
      TRUE AS flatten_json_output))
